version: "3"

services:
  miiify:
    image: jptmoore/miiify:latest
    build: .
    environment:
      - MIIIFY_BACKEND=${MIIIFY_BACKEND:-pack}
    ports:
      - "10000:10000"
    volumes:
      - ./db:/home/miiify/db
    restart: always
