version: "3"

services:
  git:
    image: jptmoore/miiify:git
    build: .
    ports:
      - "5000:5000"
      - "8080:5000"
      - "80:5000"
      - "443:5000"
    #volumes:
    #  - ./db:/home/miiify/db
    restart: always
  pack:
    image: jptmoore/miiify:pack
    build: .
    ports:
      - "5000:5000"
      - "8080:5000"
      - "80:5000"
      - "443:5000"
    #volumes:
    #  - ./db:/home/miiify/db
    restart: always
