version: "3"

services:
  miiify:
    image: jptmoore/miiify:latest
    build: .
    environment:
      - MIIIFY_BACKEND=${MIIIFY_BACKEND:-pack}
    ports:
      - "10000:10000"
    volumes:
      - miiify_data:/home/miiify/db
    restart: always

volumes:
  miiify_data:
