version: "3"

services:
  miiify:
    image: jptmoore/miiify:latest
    build: .
    environment:
      - MIIIFY_BACKEND=${MIIIFY_BACKEND:-pack}
      - MIIIFY_ID_PROTO=${MIIIFY_ID_PROTO:-https}
      - MIIIFY_PORT=${MIIIFY_PORT:-10000}
      - MIIIFY_TLS=${MIIIFY_TLS:-false}
      - MIIIFY_INTERFACE=${MIIIFY_INTERFACE:-0.0.0.0}
      - MIIIFY_REPOSITORY_NAME=${MIIIFY_REPOSITORY_NAME:-db}
      - MIIIFY_CERTIFICATE_FILE=${MIIIFY_CERTIFICATE_FILE:-server.crt}
      - MIIIFY_KEY_FILE=${MIIIFY_KEY_FILE:-server.key}
      - MIIIFY_CONTAINER_PAGE_LIMIT=${MIIIFY_CONTAINER_PAGE_LIMIT:-200}
      - MIIIFY_ACCESS_CONTROL_ALLOW_ORIGIN=${MIIIFY_ACCESS_CONTROL_ALLOW_ORIGIN:-*}
      - MIIIFY_VALIDATE_ANNOTATION=${MIIIFY_VALIDATE_ANNOTATION:-false}
    ports:
      - "10000:10000"
    volumes:
      - miiify_data:/home/miiify/db
    restart: always

volumes:
  miiify_data:
