version: "3"

services:
  miiify:
    image: ghcr.io/nationalarchives/miiify:latest
    build: .
    command:
      - "/home/miiify/miiify-serve"
      - "--repository"
      - "${MIIIFY_REPOSITORY:-pack_store}"
      - "--port"
      - "10000"
      - "--page-limit"
      - "${MIIIFY_PAGE_LIMIT:-200}"
      - "--base-url"
      - "${MIIIFY_BASE_URL:-http://localhost:10000}"
    ports:
      - "${MIIIFY_PORT:-10000}:10000"
    volumes:
      - miiify_pack:/home/miiify/pack_store
      - miiify_git:/home/miiify/git_store
      - miiify_annotations:/home/miiify/annotations
    restart: always

volumes:
  miiify_pack:
  miiify_git:
  miiify_annotations:
