version: "3"

services:
  web:
    image: jptmoore/miiify
    build: .
    ports:
      - "8080:8080"
      - "80:8080"
      - "443:8080"
    #volumes:
    #  - ./db:/home/miiify/db
    restart: always
