apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      name: proxy
    - port: 443
      targetPort: 8443
      name: proxy-ssl
    # - port: 8001
    #   name: admin-api
    # - port: 8444
    #   name: admin-api-ssl            
  selector:
    app: kong
    tier: frontend
#  type: LoadBalancer
  
